name: Rebase And Build Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Git Identity
      run: |
        git config --global user.name 'Github Automation'
        git config --global user.email 'rlaudio@users.noreply.github.com'

    - name: Install
      run: |        
        git fetch origin release
        git switch release
        npm install
        git checkout HEAD -- package-lock.json

    - name: Rebase
      run: |
        git rebase -Xtheirs main
        git status
        git push origin release

    - name: Build
      run: |
        npm run build:prod

    - name: Push
      run: |
        git add --all .
        git commit -am "Automated Release"
        git status
        git push origin release 
